name = "humanplease-reports"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
PRODUCTION_ORIGIN = "https://humanplease.wiki"
GITHUB_REPOSITORY = "Retro2512/HumanPlease"
GITHUB_BASE_BRANCH = "main"

[[d1_databases]]
binding = "DB"
database_name = "humanplease-reports"
database_id = "352d60e0-6a69-41c0-837d-05e308c522b3"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "REPORTS_KV"
id = "c42390da7b6145f2abed5645f6bceece"

[triggers]
crons = ["17 3 * * *"]

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
